#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CAPTURE_WIDTH 1280
#define CAPTURE_HEIGHT 720
#define CANNY_THRESHOLD 100
#define MIN_COLOR_SIMILARITY 90.0
#define CIRCULARITY_THRESHOLD 0.3
#define RATIO_THRESHOLD 2.0

#define X_TABLE_SIZE 1.525
#define Y_TABLE_SIZE 2.74

#endif
